
String Html_Config() {

  String html = "<html>"
  "<head>"
  "<meta id=\"Viewport\" name=\"viewport\" width=\"initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no\">"
  "<title>Video Tether</title>"
  "<style>"
  "html, body { margin: 0; padding: 0; font-size: 5vw; font-family: sans-serif; }"
  "* { font-size: inherit; }"
  "td { padding: 2vw; }"
  "input[type=number] { width: 25vw; }"
  "</style>"
  "</head>"
  "<body>"
  "<form action=\"\" method=\"post\">"
  "<table border=\"0\" style=\"width: 100vw;\">"
  "  <tr>"
  "   <td colspan=\"2\"><strong>Video Tether</strong><hr/></td>"
  " </tr>"
  " <tr>"
  "   <td>Distance</td>"
  "   <td>"
  "     <input type=\"number\" step=\"any\" name=\"distance\" value=\"" + String(distance) + "\">"
  "     <select name=\"distance_mm_multiplier\">"
  "       <option value=\"1\" " + String(distance_mm_multiplier == (float)1 ? "selected=\"true\"" : "") + ">millimeters</option>"
  "       <option value=\"1000\" " + String(distance_mm_multiplier == (float)1000 ? "selected=\"true\"" : "") + ">meters</option>"
  "       <option value=\"25.4\" " + String(distance_mm_multiplier == (float)25.4 ? "selected=\"true\"" : "") + ">inches</option>"
  "       <option value=\"304.8\" " + String(distance_mm_multiplier == (float)304.8 ? "selected=\"true\"" : "") + ">feet</option>"
  "     </select>"
  "   </td>"
  " </tr>"
  " <tr>"
  "   <td>Time</td>"
  "   <td>"
  "     <input type=\"number\" step=\"any\" name=\"duration\" value=\"" + String(duration) + "\">"
  "     <select name=\"duration_sec_multiplier\">"
  "       <option value=\"1\" " + String(duration_sec_multiplier == (float)1 ? "selected=\"true\"" : "") + ">seconds</option>"
  "       <option value=\"60\" " + String(duration_sec_multiplier == (float)60 ? "selected=\"true\"" : "") + ">minutes</option>"
  "       <option value=\"3600\" " + String(duration_sec_multiplier == (float)3600 ? "selected=\"true\"" : "") + ">hours</option>"
  "       <option value=\"86400\" " + String(duration_sec_multiplier == (float)86400 ? "selected=\"true\"" : "") + ">days</option>"
  "     </select>"
  "   </td>"
  " </tr>"
  " <tr>"
  "   <td>&nbsp;</td>"
  "   <td>"
  "     <button type=\"submit\">Start</button>"
  "   </td>"
  " </tr>"
  "</table>"
  "</form>"
  "</body>"
  "</html>";

  return html;
}


